spring:
  redis:
    host: 124.223.68.234
    port: 6379
    password: 123456
    database:
      auth_db: 0
    timeout: 5000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/*.xml
  global-config:
    banner: false
    db-config:
      logic-delete-field: is_del  # 全局逻辑删除的实体字段名
      logic-delete-value: 1       # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0   # 逻辑未删除值(默认为 0)

